version: '3.8'

services:
  mosquitto:
    container_name: mosquitto_container
    image: eclipse-mosquitto:2.0.15-openssl
    volumes:
      - ./config:/mosquitto/config/
    ports:
      - '1883:1883'
      - '8883:8883'
      - '8083:8083'
    networks:
      - default
    restart: unless-stopped

networks:
  default: